title: <p align="center"> Sreevalli Karanam </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sreevalli-karanam">LinkedIn</a> |
  <a href="https://github.com/SreevalliK">GitHub</a>
  
  <br>   
  Currently I have joined the Executive PG Programme in Machine Learning & Artificial Intelligence in Upgrad which was collaborated with IIIT Bangalore
  <br>
  </p>

theme: jekyll-theme-minimal
