title: <p align="center"> Sreevalli Karanam </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sreevalli-karanam">LinkedIn</a> |
  <a href="https://github.com/SreevalliK">GitHub</a>
  
  <br>   
  Currently working on DataScience, Machine Learning and NLP related projects
  <br>
  </p>

theme: jekyll-theme-minimal
